language: node_js
# Adicione a branch onde está a instalação do Hexo
branches:
  only:
  - BRANCH
before_install:
- npm install -g hexo
install:
- npm install
# Configure seu nome de usuário e e-mail
before_script:
- git config --global user.name 'Walter Nascimento'
- git config --global user.email 'walter.nascimento.barroso@gmail.com'
script:
- hexo generate
# Configure a Branch a ser feito o deploy
after_success:
- mkdir .deploy
- cd .deploy
- git clone --depth 1 --branch BRANCH --single-branch $DEPLOY_REPO . || (git init && git remote add -t BRANCH origin $DEPLOY_REPO)
- rm -rf ./*
- cp -r ../public/* .
- git add -A .
- git commit -m 'Site updated'
- git branch -m BRANCH
- git push -q -u origin BRANCH
